def generate_final_report(
    overall_score_results=None,
    audience_response_results=None,
    viewer_simulation_results=None,
    trend_results=None,
    attention_results=None,
    hook_results=None,
    story_results=None,
    retention_results=None,
    visual_results=None,
    title_results=None,
    thumbnail_results=None
):
    """
    Consolidates the complete video analysis into one
    final pre-publish report.

    This is an analytical report based on the signals
    generated by the existing analyzer modules.
    """

    overall_score_results = overall_score_results or {}
    audience_response_results = (
        audience_response_results or {}
    )
    viewer_simulation_results = (
        viewer_simulation_results or {}
    )
    trend_results = trend_results or {}
    attention_results = attention_results or {}
    hook_results = hook_results or {}
    story_results = story_results or {}
    retention_results = retention_results or {}
    visual_results = visual_results or {}
    title_results = title_results or {}
    thumbnail_results = thumbnail_results or {}

    # ======================================================
    # TECHNICAL / CONTENT SCORES
    # ======================================================

    technical_scores = {
        "Hook": float(
            hook_results.get(
                "hook_score",
                50
            )
        ),

        "Story": float(
            story_results.get(
                "story_score",
                50
            )
        ),

        "Retention": float(
            retention_results.get(
                "retention_score",
                50
            )
        ),

        "Visual": float(
            visual_results.get(
                "visual_score",
                50
            )
        ),

        "Title": float(
            title_results.get(
                "title_score",
                50
            )
        ),

        "Thumbnail": float(
            thumbnail_results.get(
                "thumbnail_score",
                50
            )
        )
    }

    # ======================================================
    # TECHNICAL SCORE
    # ======================================================

    technical_score = sum(
        technical_scores.values()
    ) / len(
        technical_scores
    )

    technical_score = round(
        max(
            0,
            min(
                100,
                technical_score
            )
        ),
        1
    )

    # ======================================================
    # AUDIENCE SCORE
    # ======================================================

    audience_score = float(
        audience_response_results.get(
            "audience_response_score",
            viewer_simulation_results.get(
                "viewer_response_score",
                50
            )
        )
    )

    audience_score = round(
        max(
            0,
            min(
                100,
                audience_score
            )
        ),
        1
    )

    # ======================================================
    # TREND SCORE
    # ======================================================

    trend_score = float(
        trend_results.get(
            "trend_score",
            50
        )
    )

    trend_score = round(
        max(
            0,
            min(
                100,
                trend_score
            )
        ),
        1
    )

    # ======================================================
    # ATTENTION SCORE
    # ======================================================

    attention_score = float(
        attention_results.get(
            "attention_score",
            50
        )
    )

    attention_score = round(
        max(
            0,
            min(
                100,
                attention_score
            )
        ),
        1
    )

    # ======================================================
    # FINAL COMBINED SCORE
    # ======================================================

    final_score = (
        technical_score * 0.30
        + audience_score * 0.40
        + trend_score * 0.15
        + attention_score * 0.15
    )

    final_score = round(
        max(
            0,
            min(
                100,
                final_score
            )
        ),
        1
    )

    # ======================================================
    # SCORE CATEGORY
    # ======================================================

    if final_score >= 85:
        score_category = "Very Strong"

    elif final_score >= 75:
        score_category = "Strong"

    elif final_score >= 65:
        score_category = "Moderate"

    elif final_score >= 50:
        score_category = "Needs Improvement"

    else:
        score_category = "High Risk"

    # ======================================================
    # ALL COMPONENTS
    # ======================================================

    component_scores = {
        **technical_scores,

        "Audience Response": audience_score,
        "Trend Patterns": trend_score,
        "Attention": attention_score
    }

    # ======================================================
    # STRONGEST AREAS
    # ======================================================

    strongest_areas = sorted(
        component_scores.items(),
        key=lambda item: item[1],
        reverse=True
    )[:5]

    # ======================================================
    # WEAKEST AREAS
    # ======================================================

    weakest_areas = sorted(
        component_scores.items(),
        key=lambda item: item[1]
    )[:5]

    # ======================================================
    # PRIORITY IMPROVEMENTS
    # ======================================================

    priority_improvements = []

    if hook_results.get(
        "hook_score",
        50
    ) < 70:

        priority_improvements.append(
            "Strengthen the opening hook and deliver "
            "clear value or curiosity within the first few seconds."
        )

    if retention_results.get(
        "retention_score",
        50
    ) < 70:

        priority_improvements.append(
            "Review potential retention-drop sections "
            "and tighten slower parts of the video."
        )

    if story_results.get(
        "story_score",
        50
    ) < 70:

        priority_improvements.append(
            "Improve narrative progression and make "
            "the payoff more clearly connected to the setup."
        )

    if visual_results.get(
        "visual_score",
        50
    ) < 70:

        priority_improvements.append(
            "Improve visual consistency, framing or "
            "visual variation where needed."
        )

    if title_results.get(
        "title_score",
        50
    ) < 70:

        priority_improvements.append(
            "Strengthen title clarity and the central "
            "value or curiosity signal."
        )

    if thumbnail_results.get(
        "thumbnail_score",
        50
    ) < 70:

        priority_improvements.append(
            "Improve thumbnail clarity, focal point "
            "and visual communication."
        )

    if audience_score < 70:

        priority_improvements.append(
            "Strengthen the elements that drive audience "
            "attention, curiosity, emotional response and relevance."
        )

    if trend_score < 70:

        priority_improvements.append(
            "Review the detected differences from generalized "
            "high-engagement content patterns."
        )

    if attention_score < 70:

        priority_improvements.append(
            "Review estimated attention-risk points and "
            "strengthen transitions or payoff moments."
        )

    if not priority_improvements:

        priority_improvements.append(
            "No major weakness was detected across the "
            "current analysis signals."
        )

    # ======================================================
    # AUDIENCE INSIGHTS
    # ======================================================

    audience_potential = (
        audience_response_results.get(
            "audience_potential",
            "Unknown"
        )
    )

    audience_weakest = (
        audience_response_results.get(
            "weakest_areas",
            []
        )
    )

    audience_strongest = (
        audience_response_results.get(
            "strongest_areas",
            []
        )
    )

    # ======================================================
    # TREND INSIGHTS
    # ======================================================

    pattern_matches = (
        trend_results.get(
            "pattern_matches",
            []
        )
    )

    pattern_warnings = (
        trend_results.get(
            "pattern_warnings",
            []
        )
    )

    # ======================================================
    # ATTENTION INSIGHTS
    # ======================================================

    attention_risks = (
        attention_results.get(
            "attention_risks",
            []
        )
    )

    attention_recoveries = (
        attention_results.get(
            "attention_recoveries",
            []
        )
    )

    # ======================================================
    # OVERALL ASSESSMENT
    # ======================================================

    if final_score >= 85:

        assessment = (
            "The combined analysis shows strong signals across "
            "technical quality, audience response, attention "
            "and generalized engagement patterns."
        )

    elif final_score >= 75:

        assessment = (
            "The video demonstrates several strong performance "
            "signals, with some areas that can still be optimized "
            "before publishing."
        )

    elif final_score >= 65:

        assessment = (
            "The video has a mixed performance profile. "
            "Several components are functioning well while "
            "other areas may limit audience engagement."
        )

    elif final_score >= 50:

        assessment = (
            "The analysis identifies multiple areas that "
            "could be improved before publishing."
        )

    else:

        assessment = (
            "The current signals indicate substantial areas "
            "for improvement across the analyzed dimensions."
        )

    # ======================================================
    # CONFIDENCE
    # ======================================================

    available_modules = sum([
        bool(overall_score_results),
        bool(audience_response_results),
        bool(viewer_simulation_results),
        bool(trend_results),
        bool(attention_results),
        bool(hook_results),
        bool(story_results),
        bool(retention_results),
        bool(visual_results),
        bool(title_results),
        bool(thumbnail_results)
    ])

    if available_modules >= 10:

        confidence = "Moderate"

    elif available_modules >= 7:

        confidence = "Low-Moderate"

    else:

        confidence = "Low"

    return {
        "final_score": final_score,

        "score_category": score_category,

        "technical_score": technical_score,

        "audience_score": audience_score,

        "trend_score": trend_score,

        "attention_score": attention_score,

        "component_scores": component_scores,

        "strongest_areas": [
            {
                "area": area,
                "score": score
            }
            for area, score in strongest_areas
        ],

        "weakest_areas": [
            {
                "area": area,
                "score": score
            }
            for area, score in weakest_areas
        ],

        "priority_improvements":
            priority_improvements,

        "audience_potential":
            audience_potential,

        "audience_strongest":
            audience_strongest,

        "audience_weakest":
            audience_weakest,

        "pattern_matches":
            pattern_matches,

        "pattern_warnings":
            pattern_warnings,

        "attention_risks":
            attention_risks,

        "attention_recoveries":
            attention_recoveries,

        "assessment":
            assessment,

        "confidence":
            confidence,

        "status":
            "Final report generated successfully"
    }